theme: minima
title: Projets Data for Good
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dataforgoodfr.github.io" # the base hostname & protocol for your site
twitter_username: dataforgoodfr

# Build settings
markdown: kramdown

collections:
  projects:
    output: true


defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      image: default.jpeg
