title: Data for Good
description: Digital al servicio del interés general
author: Data for Good
twitter:
  username: DataForGood_BCN
logo: /img/logo.png
social:
  links:
    - https://twitter.com/DataForGood_BCN
google_site_verification:
lang: es_ES

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
  members:
    output: true

number_of_season: 4

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
